name: Build App
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    continue-on-error: true
    strategy:
      fail-fast: true
      matrix:
        platform: [x64, x86]
        configuration: [Release]
    steps:
      - uses: actions/checkout@v7.0.0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.x
      - uses: microsoft/setup-msbuild@v3
      - name: Build solution
        run: msbuild /restore Ishiyama.slnx /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} /p:SelfContained=true /p:TargetFramework=net10.0-windows10.0.26100.0
      - name: Package solution
        run: msbuild /restore Ishiyama.slnx /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} /p:SelfContained=true /p:TargetFramework=net10.0-windows10.0.26100.0 /p:GenerateAppxPackageOnBuild=true
      - name: Upload the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AppPackages
          path: Ishiyama\AppPackages\**\*.*
