name: Build App
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x64]
        configuration: [Release]
    steps:
      - uses: actions/checkout@v7.0.0
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x
      - uses: microsoft/setup-msbuild@v3
      - run: msbuild -p:Configuration=${{ matrix.configuration }} -p:Platform=${{ matrix.platform }} -p:TargetFramework=net10.0 -r Ishiyama.slnx
      - run: msbuild -p:Configuration=${{ matrix.configuration }} -p:Platform=${{ matrix.platform }} -p:SelfContained=true Ishiyama.slnx
      - name: Upload the artifacts
        uses: actions/upload-artifact@v7
        with:
          path: packages?/*
